this._s=this._s||{};(function(_){var window=this;
try{
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
/*

 Copyright 2024 Google, Inc
 SPDX-License-Identifier: MIT
*/
/*
 SPDX-License-Identifier: Apache-2.0
*/
/*
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
/*

 Copyright Google LLC All Rights Reserved.

 Use of this source code is governed by an MIT-style license that can be
 found in the LICENSE file at https://angular.dev/license
*/
var baa,caa,zaa,Caa,Daa,Eaa,Faa,Gaa,Haa,Iaa,Jaa,Kaa,Oaa,Maa,Laa,Paa,Naa,Qaa,Saa,Raa,Taa,Uaa,Vaa,Xaa,Yaa,dba,pba,tba,Cba,Eba,Fba,Gba,Jba,Mba,Nba,Sba,Xba,Zba,cca,eca,fca,hca,dca,jca,lca,$ba,mca,nca,uca,xca,yca,zca,Bca,Cca,Eca,Fca,Gca,Ica,Rca,dda,eda,gda,hda,ida,ada,kda,Yca,lda,Wca,Zca,$ca,mda,nda,pda,tda,Bda,Cda,Dda,Eda,Gda,Kda,Mda,eb,Pda,Qda,Sda,Rda,Wda,Xda,Yda,Zda,$da,aea,bea,cea,gea,jea,lea,mea,tea,xea,zea,yea,Aea,Eea,Iea,Lea,Pea,Nea,Rea,Oea,Qea,Tea,Sea,bfa,Xea,Zea,cfa,ffa,gfa,mfa,ofa,qfa,pfa,rfa,
sfa,tfa,afa,Bfa,Efa,Afa,Jfa,Lfa,Mfa,Sfa,Pfa,Yfa,Wfa,Xfa,Zfa,aga,bga,fga,hga,jga,lga,nga,pga,tga,wga,Dga,Jga,Lga,Mga,Oga,Qga,Rga,Sga,Uga,gha,iha,kha,pha,rha,tha,wha,Bha,Cha,Eha,Hha,Uha,bia,Zha,dia,Ub,hia,kia,mia,dc,Eia,Gia,Sia,Xia,$ia,aja,bja,cja,dja,pja,oja,uja,vja,wja,Pja,Sja,Uja,lka,Yc,Aka,Bka,Ika,Gka,Fka,Kka,Tka,Uka,Vka,Zka,ala,mla,pla,rla,ula,wla,xla,yla,Ela,Mla,Rla,Lla,Sla,kma,tma,wma,uma,yma,Hma,Lma,Nma,Oma,Sma,$ma,ana,bna,fna,Cna,Dna,Fna,Gna,Pna,Ona,Qna,Sna,Tna,Zna,coa,doa,goa,loa,moa,noa,
roa,Boa,Eoa,Foa,Hoa,Loa,Koa,Noa,Ooa,Woa,Voa,Zoa,Xoa,$oa,bpa,hpa,ipa,apa,mpa,Apa,Gpa,Ipa,Jpa,Lpa,Mpa,Tpa,Qpa,Rpa,Spa,Upa,Opa,Wpa,Xpa,dqa,hqa,jqa,pqa,rqa,nqa,Aqa,Bqa,Cqa,Dqa,Sqa,Tqa,Mqa,Zqa,Rqa,ira,tra,sra,pra,ura,wra,Cra,Ira,Kra,Jra,Lra,Rra,Sra,Tra,Ura,Wra,Xra,Zra,esa,dsa,jsa,msa,nsa,usa,vsa,wsa,zsa,Bsa,Csa,Dsa,Esa,Gsa,Lsa,Msa,Ssa,Wsa,ita,jta,kta,lta,mta,pta,qta,sta,uta,yta,Bta,zta,Fta,Nta,Ota,Qta,Wta,Xta,$ta,cua,dua,eua,hua,lua,mua,pua,xua,Iua,Gua,Qua,Sua,Tua,Uua,cva,iva,qva,sva,uva,wva,xva,Bva,Dva,
Mva,Ova,Pva,Qva,Rva,Yva,Zva,awa,cwa,dwa,ewa,fwa,iwa,kwa,lwa,owa,qwa,wwa,zwa,Awa,Ewa,Fwa,Hwa,Iwa,Kwa,Lwa,Nwa,Owa,Swa,Wwa,Zwa,$wa,bxa,fxa,gxa,hxa,ixa,kxa,nxa,oxa,uxa,Axa,Bxa,Exa,Fxa,Gxa,Hxa,Jxa,Mxa,Kxa,Wxa,Zxa,jya,kya,lya,mya,Fh,nya,oya,pya,qya,rya,tya;_.ba=function(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,_.ba);else{const c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));b!==void 0&&(this.cause=b)};
_.aaa=function(a,b){a=a.split("%s");let c="";const d=a.length-1;for(let e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");_.ba.call(this,c+a[d])};baa=function(a,b){if(a)throw Error("s");b.push(65533)};caa=function(a,b){b=String.fromCharCode.apply(null,b);return a==null?b:a+b};
_.daa=function(a,b,c,d){c=b+c;const e=[];let f=null;let g,h,k;for(;b<c;){var l=a[b++];l<128?e.push(l):l<224?b>=c?baa(d,e):(g=a[b++],l<194||(g&192)!==128?(b--,baa(d,e)):e.push((l&31)<<6|g&63)):l<240?b>=c-1?baa(d,e):(g=a[b++],(g&192)!==128||l===224&&g<160||l===237&&g>=160||((h=a[b++])&192)!==128?(b--,baa(d,e)):e.push((l&15)<<12|(g&63)<<6|h&63)):l<=244?b>=c-2?baa(d,e):(g=a[b++],(g&192)!==128||(l<<28)+(g-144)>>30!==0||((h=a[b++])&192)!==128||((k=a[b++])&192)!==128?(b--,baa(d,e)):(l=(l&7)<<18|(g&63)<<
12|(h&63)<<6|k&63,l-=65536,e.push((l>>10&1023)+55296,(l&1023)+56320))):baa(d,e);e.length>=8192&&(f=caa(f,e),e.length=0)}return caa(f,e)};
_.haa=function(a,b,c,d){var e;d?(e=eaa)||(e=eaa=new TextDecoder("utf-8",{fatal:!0})):(e=faa)||(e=faa=new TextDecoder("utf-8",{fatal:!1}));c=b+c;a=b===0&&c===a.length?a:a.subarray(b,c);try{return e.decode(a)}catch(f){if(b=d){if(gaa===void 0){try{e.decode(new Uint8Array([128]))}catch(g){}try{e.decode(new Uint8Array([97])),gaa=!0}catch(g){gaa=!1}}b=!gaa}b&&(eaa=void 0);throw f;}};
_.laa=function(a,b=!1){if(iaa){if(b&&(jaa?!a.isWellFormed():/(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])/.test(a)))throw Error("t");a=(kaa||(kaa=new TextEncoder)).encode(a)}else{let d=0;const e=new Uint8Array(3*a.length);for(let f=0;f<a.length;f++){var c=a.charCodeAt(f);if(c<128)e[d++]=c;else{if(c<2048)e[d++]=c>>6|192;else{if(c>=55296&&c<=57343){if(c<=56319&&f<a.length){const g=a.charCodeAt(++f);if(g>=56320&&g<=57343){c=(c-55296)*1024+g-56320+65536;e[d++]=c>>18|240;e[d++]=
c>>12&63|128;e[d++]=c>>6&63|128;e[d++]=c&63|128;continue}else f--}if(b)throw Error("t");c=65533}e[d++]=c>>12|224;e[d++]=c>>6&63|128}e[d++]=c&63|128}}a=d===e.length?e:e.subarray(0,d)}return a};_.da=function(a){_.ca.setTimeout(()=>{throw a;},0)};_.ea=function(a,b){return a.lastIndexOf(b,0)==0};_.maa=function(a,b){const c=a.length-b.length;return c>=0&&a.indexOf(b,c)==c};_.oaa=function(a,b){return _.naa(b,a.slice(0,b.length))==0};_.paa=function(a,b){return a.toLowerCase()==b.toLowerCase()};_.fa=function(a){return/^[\s\xa0]*$/.test(a)};
_.naa=function(a,b){a=String(a).toLowerCase();b=String(b).toLowerCase();return a<b?-1:a==b?0:1};_.xaa=function(a){if(!qaa.test(a))return a;a.indexOf("&")!=-1&&(a=a.replace(raa,"&amp;"));a.indexOf("<")!=-1&&(a=a.replace(saa,"&lt;"));a.indexOf(">")!=-1&&(a=a.replace(taa,"&gt;"));a.indexOf('"')!=-1&&(a=a.replace(uaa,"&quot;"));a.indexOf("'")!=-1&&(a=a.replace(vaa,"&#39;"));a.indexOf("\x00")!=-1&&(a=a.replace(waa,"&#0;"));return a};_.ia=function(a,b){return a.indexOf(b)!=-1};
_.yaa=function(a,b){return _.ia(a.toLowerCase(),b.toLowerCase())};
_.Aaa=function(a,b){let c=0;a=_.ja(String(a)).split(".");b=_.ja(String(b)).split(".");const d=Math.max(a.length,b.length);for(let g=0;c==0&&g<d;g++){var e=a[g]||"",f=b[g]||"";do{e=/(\d*)(\D*)(.*)/.exec(e)||["","","",""];f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];if(e[0].length==0&&f[0].length==0)break;c=zaa(e[1].length==0?0:parseInt(e[1],10),f[1].length==0?0:parseInt(f[1],10))||zaa(e[2].length==0,f[2].length==0)||zaa(e[2],f[2]);e=e[3];f=f[3]}while(c==0)}return c};
zaa=function(a,b){return a<b?-1:a>b?1:0};_.la=function(){var a=_.ca.navigator;return a&&(a=a.userAgent)?a:""};Caa=function(a){if(!_.Baa||!_.na)return!1;for(let b=0;b<_.na.brands.length;b++){const {brand:c}=_.na.brands[b];if(c&&_.ia(c,a))return!0}return!1};_.oa=function(a){return _.ia(_.la(),a)};Daa=function(a){const b=RegExp("([A-Z][\\w ]+)/([^\\s]+)\\s*(?:\\((.*?)\\))?","g"),c=[];let d;for(;d=b.exec(a);)c.push([d[1],d[2],d[3]||void 0]);return c};
Eaa=function(a=!1){return a||_.Baa?!!_.na&&_.na.brands.length>0:!1};Faa=function(){return Eaa()?!1:_.oa("Opera")};Gaa=function(){return Eaa()?!1:_.oa("Trident")||_.oa("MSIE")};Haa=function(){return Eaa()?!1:_.oa("Edge")};Iaa=function(){return Eaa()?Caa("Microsoft Edge"):_.oa("Edg/")};Jaa=function(){return Eaa()?Caa("Opera"):_.oa("OPR")};Kaa=function(){return _.oa("Firefox")||_.oa("FxiOS")};Oaa=function(){return _.oa("Safari")&&!(Laa()||Maa()||Faa()||Haa()||Iaa()||Jaa()||Kaa()||Naa()||_.oa("Android"))};
Maa=function(){return Eaa()?!1:_.oa("Coast")};Laa=function(){return Eaa()?Caa("Chromium"):(_.oa("Chrome")||_.oa("CriOS"))&&!Haa()||Naa()};Paa=function(){return _.oa("Android")&&!(Laa()||Kaa()||Faa()||Naa())};Naa=function(){return _.oa("Silk")};Qaa=function(a){const b={};a.forEach(c=>{b[c[0]]=c[1]});return c=>b[c.find(d=>d in b)]||""};
Saa=function(){var a=_.la();if(Gaa())return Raa(a);a=Daa(a);const b=Qaa(a);return Faa()?b(["Version","Opera"]):Haa()?b(["Edge"]):Iaa()?b(["Edg"]):Naa()?b(["Silk"]):Laa()?b(["Chrome","CriOS","HeadlessChrome"]):(a=a[2])&&a[1]||""};
Raa=function(a){var b=/rv: *([\d\.]*)/.exec(a);if(b&&b[1])return b[1];b="";const c=/MSIE +([\d\.]+)/.exec(a);if(c&&c[1])if(a=/Trident\/(\d.\d)/.exec(a),c[1]=="7.0")if(a&&a[1])switch(a[1]){case "4.0":b="8.0";break;case "5.0":b="9.0";break;case "6.0":b="10.0";break;case "7.0":b="11.0"}else b="7.0";else b=c[1];return b};
Taa=function(a){var b=_.la();if(a==="Internet Explorer")return Gaa()?Raa(b):"";b=Daa(b);const c=Qaa(b);switch(a){case "Opera":if(Faa())return c(["Version","Opera"]);if(Jaa())return c(["OPR"]);break;case "Microsoft Edge":if(Haa())return c(["Edge"]);if(Iaa())return c(["Edg"]);break;case "Chromium":if(Laa())return c(["Chrome","CriOS","HeadlessChrome"])}return a==="Firefox"&&Kaa()||a==="Safari"&&Oaa()||a==="Android Browser"&&Paa()||a==="Silk"&&Naa()?(a=b[2])&&a[1]||"":""};
Uaa=function(a){if(Eaa()&&a!=="Silk"){var b=_.na.brands.find(({brand:c})=>c===a);if(!b||!b.version)return NaN;b=b.version.split(".")}else{b=Taa(a);if(b==="")return NaN;b=b.split(".")}return b.length===0?NaN:Number(b[0])};Vaa=function(a,b){return Uaa(a)>=b};Xaa=function(a){let b="";Vaa("Chromium",98)||(b=Taa(a));const c=a!=="Silk"&&Eaa(!0);if(c){if(!_.na.brands.find(({brand:d})=>d===a))return}else if(b==="")return;return new Waa(a,c,b)};Yaa=function(){return _.Baa?!!_.na&&!!_.na.platform:!1};
_.pa=function(){return Yaa()?_.na.platform==="Android":_.oa("Android")};_.Zaa=function(){return _.oa("iPod")};_.$aa=function(){return _.oa("iPhone")&&!_.oa("iPod")&&!_.oa("iPad")};_.qa=function(){return _.$aa()||_.oa("iPad")||_.Zaa()};_.aba=function(){return Yaa()?_.na.platform==="macOS":_.oa("Macintosh")};_.bba=function(){return Yaa()?_.na.platform==="Linux":_.oa("Linux")};_.cba=function(){return Yaa()?_.na.platform==="Windows":_.oa("Windows")};
dba=function(){return Yaa()?_.na.platform==="Chrome OS":_.oa("CrOS")};
_.eba=function(){var a=_.la(),b="";_.cba()?(b=/Windows (?:NT|Phone) ([0-9.]+)/,b=(a=b.exec(a))?a[1]:"0.0"):_.qa()?(b=/(?:iPhone|iPod|iPad|CPU)\s+OS\s+(\S+)/,b=(a=b.exec(a))&&a[1].replace(/_/g,".")):_.aba()?(b=/Mac OS X ([0-9_.]+)/,b=(a=b.exec(a))?a[1].replace(/_/g,"."):"10"):_.yaa(_.la(),"KaiOS")?(b=/(?:KaiOS)\/(\S+)/i,b=(a=b.exec(a))&&a[1]):_.pa()?(b=/Android\s+([^\);]+)(\)|;)/,b=(a=b.exec(a))&&a[1]):dba()&&(b=/(?:CrOS\s+(?:i686|x86_64)\s+([0-9.]+))/,b=(a=b.exec(a))&&a[1]);return b||""};
_.fba=function(a){return _.Aaa(_.eba(),a)>=0};_.ra=function(a){return a[a.length-1]};_.ua=function(a,b,c){var d=a.length;const e=typeof a==="string"?a.split(""):a;for(--d;d>=0;--d)d in e&&b.call(c,e[d],d,a)};_.wa=function(a,b,c){b=_.va(a,b,c);return b<0?null:typeof a==="string"?a.charAt(b):a[b]};_.va=function(a,b,c){const d=a.length,e=typeof a==="string"?a.split(""):a;for(let f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};
_.hba=function(a,b,c){b=_.gba(a,b,c);return b<0?null:typeof a==="string"?a.charAt(b):a[b]};_.gba=function(a,b,c){var d=a.length;const e=typeof a==="string"?a.split(""):a;for(--d;d>=0;d--)if(d in e&&b.call(c,e[d],d,a))return d;return-1};_.ya=function(a,b){return _.xa(a,b)>=0};_.iba=function(a){if(!Array.isArray(a))for(let b=a.length-1;b>=0;b--)delete a[b];a.length=0};_.jba=function(a,b){_.ya(a,b)||a.push(b)};_.Aa=function(a,b){b=_.xa(a,b);let c;(c=b>=0)&&_.za(a,b);return c};
_.za=function(a,b){return Array.prototype.splice.call(a,b,1).length==1};_.kba=function(a,b){b=_.va(a,b);return b>=0?(_.za(a,b),!0):!1};_.lba=function(a,b){let c=0;_.ua(a,function(d,e){b.call(void 0,d,e,a)&&_.za(a,e)&&c++});return c};_.Ba=function(a){return Array.prototype.concat.apply([],arguments)};_.mba=function(a){return Array.prototype.concat.apply([],arguments)};_.Da=function(a){const b=a.length;if(b>0){const c=Array(b);for(let d=0;d<b;d++)c[d]=a[d];return c}return[]};
_.Fa=function(a,b){for(let c=1;c<arguments.length;c++){const d=arguments[c];if(_.Ea(d)){const e=a.length||0,f=d.length||0;a.length=e+f;for(let g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}};_.Ga=function(a,b,c,d){return Array.prototype.splice.apply(a,_.nba(arguments,1))};_.nba=function(a,b,c){return arguments.length<=2?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};
_.oba=function(a,b,c){b=b||a;var d=g=>g;c=c||d;let e=d=0;const f=new Set;for(;e<a.length;){const g=a[e++],h=c(g);f.has(h)||(f.add(h),b[d++]=g)}b.length=d};_.Ha=function(a,b,c){return pba(a,c||_.qba,!1,b)};_.rba=function(a,b,c){return pba(a,b,!0,void 0,c)};pba=function(a,b,c,d,e){let f=0,g=a.length,h;for(;f<g;){const k=f+(g-f>>>1);let l;c?l=b.call(e,a[k],k,a):l=b(d,a[k]);l>0?f=k+1:(g=k,h=!l)}return h?f:-f-1};_.sba=function(a,b){a.sort(b||_.qba)};
_.Ia=function(a,b,c){if(!_.Ea(a)||!_.Ea(b)||a.length!=b.length)return!1;const d=a.length;c=c||tba;for(let e=0;e<d;e++)if(!c(a[e],b[e]))return!1;return!0};_.qba=function(a,b){return a>b?1:a<b?-1:0};tba=function(a,b){return a===b};_.uba=function(a,b){const c={};_.Ja(a,function(d,e){c[b.call(void 0,d,e,a)]=d});return c};_.Ka=function(a,b,c){const d=[];let e=0,f=a;c=c||1;b!==void 0&&(e=a,f=b);if(c*(f-e)<0)return[];if(c>0)for(a=e;a<f;a+=c)d.push(a);else for(a=e;a>f;a+=c)d.push(a);return d};
_.vba=function(a,b){const c=[];for(let d=0;d<b;d++)c[d]=a;return c};_.wba=function(a){const b=[];for(let d=0;d<arguments.length;d++){const e=arguments[d];if(Array.isArray(e))for(let f=0;f<e.length;f+=8192){var c=_.nba(e,f,f+8192);c=_.wba.apply(null,c);for(let g=0;g<c.length;g++)b.push(c[g])}else b.push(e)}return b};_.yba=function(a){const b=Math.random;for(let c=a.length-1;c>0;c--){const d=Math.floor(b()*(c+1)),e=a[c];a[c]=a[d];a[d]=e}};_.zba=function(){return _.yaa(_.la(),"WebKit")&&!_.oa("Edge")};
_.Aba=function(){return _.oa("Gecko")&&!_.zba()&&!(_.oa("Trident")||_.oa("MSIE"))&&!_.oa("Edge")};Cba=function(a){return Bba[a]||""};Eba=function(a){a=Dba.test(a)?a.replace(Dba,Cba):a;a=atob(a);const b=new Uint8Array(a.length);for(let c=0;c<a.length;c++)b[c]=a.charCodeAt(c);return b};Fba=function(a){return a!=null&&a instanceof Uint8Array};Gba=function(a,b){const c=a.length;if(c!==b.length)return!1;for(let d=0;d<c;d++)if(a[d]!==b[d])return!1;return!0};
Jba=function(a){return a.length==0?_.Hba():new _.La(a,_.Iba)};
Mba=function(a,b){if(typeof a==="string")return new Kba(Eba(a),b);if(Array.isArray(a))return new Kba(new Uint8Array(a),b);if(a.constructor===Uint8Array)return new Kba(a,!1);if(a.constructor===ArrayBuffer)return a=new Uint8Array(a),new Kba(a,!1);if(a.constructor===_.La)return b=_.Lba(a)||new Uint8Array(0),new Kba(b,!0,a);if(a instanceof Uint8Array)return a=a.constructor===Uint8Array?a:new Uint8Array(a.buffer,a.byteOffset,a.byteLength),new Kba(a,!1);throw Error();};
Nba=function(){return typeof BigInt==="function"};_.Pba=function(a,b){const c=Oba;if(!b(a)){var d,e;b=(e=(d=typeof c==="function"?c():c)==null?void 0:d.concat("\n"))!=null?e:"";throw Error("A`"+b+"`"+String(a));}};_.Qba=function(a){const b=Oba;if(!a)throw Error((typeof b==="function"?b():b)||String(a));};Sba=function(a){_.Pba(a,_.Rba);return a};_.Ma=function(a){a.qUf=!0;return a};
_.Na=function(a){var b=a;if((0,_.Tba)(b)){if(!/^\s*(?:-?[1-9]\d*|0)?\s*$/.test(b))throw Error(String(b));}else if((0,_.Uba)(b)&&!Number.isSafeInteger(b))throw Error(String(b));return _.Vba?BigInt(a):a=Wba(a)?a?"1":"0":(0,_.Tba)(a)?a.trim()||"0":String(a)};Xba=function(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(let c=0;c<a.length;c++){const d=a[c],e=b[c];if(d>e)return!1;if(d<e)return!0}};_.Yba=function(a,b,c){return b===c?new Uint8Array(0):a.slice(b,c)};
Zba=function(a){const b=a>>>0;_.Oa=b;_.Pa=(a-b)/4294967296>>>0};_.aca=function(a){if(a<0){Zba(-a);const [b,c]=$ba(_.Oa,_.Pa);_.Oa=b>>>0;_.Pa=c>>>0}else Zba(a)};cca=function(a){const b=bca||(bca=new DataView(new ArrayBuffer(8)));b.setFloat32(0,+a,!0);_.Pa=0;_.Oa=b.getUint32(0,!0)};eca=function(a,b){const c=b*4294967296+(a>>>0);return Number.isSafeInteger(c)?c:dca(a,b)};
fca=function(a,b){const c=b&2147483648;c&&(a=~a+1>>>0,b=~b>>>0,a==0&&(b=b+1>>>0));a=eca(a,b);return typeof a==="number"?c?-a:a:c?"-"+a:a};_.gca=function(a){return(a<<1^a>>31)>>>0};hca=function(a){var b=_.Oa,c=_.Pa;const d=c>>31;c=(c<<1|b>>>31)^d;a(b<<1^d,c)};_.ica=function(a,b){const c=-(a&1);a=(a>>>1|b<<31)^c;b=b>>>1^c;return fca(a,b)};
dca=function(a,b){b>>>=0;a>>>=0;if(b<=2097151)var c=""+(4294967296*b+a);else Nba()?c=""+(BigInt(b)<<BigInt(32)|BigInt(a)):(c=(a>>>24|b<<8)&16777215,b=b>>16&65535,a=(a&16777215)+c*6777216+b*6710656,c+=b*8147497,b*=2,a>=1E7&&(c+=a/1E7>>>0,a%=1E7),c>=1E7&&(b+=c/1E7>>>0,c%=1E7),c=b+jca(c)+jca(a));return c};jca=function(a){a=String(a);return"0000000".slice(a.length)+a};
_.kca=function(a,b){if(b&2147483648)if(Nba())a=""+(BigInt(b|0)<<BigInt(32)|BigInt(a>>>0));else{const [c,d]=$ba(a,b);a="-"+dca(c,d)}else a=dca(a,b);return a};
lca=function(a){if(a.length<16)_.aca(Number(a));else if(Nba())a=BigInt(a),_.Oa=Number(a&BigInt(4294967295))>>>0,_.Pa=Number(a>>BigInt(32)&BigInt(4294967295));else{const b=+(a[0]==="-");_.Pa=_.Oa=0;const c=a.length;for(let d=b,e=(c-b)%6+b;e<=c;d=e,e+=6){const f=Number(a.slice(d,e));_.Pa*=1E6;_.Oa=_.Oa*1E6+f;_.Oa>=4294967296&&(_.Pa+=Math.trunc(_.Oa/4294967296),_.Pa>>>=0,_.Oa>>>=0)}if(b){const [d,e]=$ba(_.Oa,_.Pa);_.Oa=d;_.Pa=e}}};$ba=function(a,b){b=~b;a?a=~a+1:b+=1;return[a,b]};
_.Qa=function(a,b=!1){return b&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol()};mca=function(a,b){a[_.Sa]|=b};nca=function(a){if(4&a)return 512&a?512:1024&a?1024:0};_.oca=function(a){mca(a,34);return a};_.pca=function(a){mca(a,32);return a};_.sca=function(a){return a!=null&&a[_.qca]===_.rca};_.Ta=function(a,b){return b===void 0?a.Nb!==tca&&!!(2&(a.Rq[_.Sa]|0)):!!(2&b)&&a.Nb!==tca};uca=function(a,b){a.Nb=b?tca:void 0};
xca=function(a,b,c){if(a==null){if(!c)throw Error();}else if(typeof a==="string")a=_.vca(a);else if(a.constructor!==_.La)if(Fba(a))a=_.wca(a);else{if(!b)throw Error();a=void 0}return a};yca=function(a){return!1};zca=function(a,b){if(!Array.isArray(a)||a.length)return!1;const c=a[_.Sa]|0;if(c&1)return!0;if(!yca(b))return!1;a[_.Sa]=c|1;return!0};_.Aca=function(a,b){if(typeof b!=="number"||b<0||b>=a.length)throw Error();};Bca=function(a,b){if(typeof b!=="number"||b<0||b>a.length)throw Error();};
Cca=function(a,b,c){const d=b&128?0:-1,e=a.length;var f;if(f=!!e)f=a[e-1],f=f!=null&&typeof f==="object"&&f.constructor===Object;const g=e+(f?-1:0);for(b=b&128?1:0;b<g;b++)c(b-d,a[b]);if(f){a=a[e-1];for(const h in a)!isNaN(h)&&c(+h,a[h])}};_.Dca=function(a){return a&128?_.Ua:void 0};Eca=function(a,b){a.__closure__error__context__984382||(a.__closure__error__context__984382={});a.__closure__error__context__984382.severity=b};Fca=function(){const a=Error();Eca(a,"incident");_.da(a)};
Gca=function(a){a=Error(a);Eca(a,"warning");return a};Ica=function(a,b){if(a!=null){var c;var d=(c=Hca)!=null?c:Hca={};c=d[a]||0;c>=b||(d[a]=c+1,Fca())}};_.Xa=function(a){return _.Wa(a,void 0)};_.Wa=function(a,b=`unexpected value ${a}!`){throw Error(b);};_.Jca=function(a){if(typeof a!=="number")throw Error("B`"+typeof a+"`"+a);return a};_.Kca=function(a){if(a==null||typeof a==="number")return a;if(a==="NaN"||a==="Infinity"||a==="-Infinity")return Number(a)};
_.Lca=function(a){if(a==null||a instanceof _.La)return a;if(typeof a==="string")return _.vca(a)};_.Nca=function(a){if(typeof a!=="boolean")throw Error("C`"+_.Mca(a)+"`"+a);return a};_.Oca=function(a){if(a==null||typeof a==="boolean")return a;if(typeof a==="number")return!!a};Rca=function(a){switch(typeof a){case "bigint":return!0;case "number":return Pca(a);case "string":return Qca.test(a);default:return!1}};_.Sca=function(a){if(!Pca(a))throw Gca("enum");return a|0};
_.Tca=function(a){return a==null?a:Pca(a)?a|0:void 0};_.Uca=function(a){if(typeof a!=="number")throw Gca("int32");if(!Pca(a))throw Gca("int32");return a|0};_.Ya=function(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return Pca(a)?a|0:void 0};_.Za=function(a){if(typeof a!=="number")throw Gca("uint32");if(!Pca(a))throw Gca("uint32");return a>>>0};_.Vca=function(a){return a==null?a:_.Za(a)};
_.ab=function(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return Pca(a)?a>>>0:void 0};
_.bda=function(a,b=0){if(!Rca(a))throw Gca("int64");const c=typeof a;switch(b){case 512:switch(c){case "string":return Wca(a);case "bigint":return String(Xca(64,a));default:return Yca(a)}case 1024:switch(c){case "string":return Zca(a);case "bigint":return _.Na(Xca(64,a));default:return $ca(a)}case 0:switch(c){case "string":return Wca(a);case "bigint":return _.Na(Xca(64,a));default:return ada(a)}default:return _.Wa(b,"Unknown format requested type for int64")}};
_.cda=function(a){return a==null?a:_.bda(a,0)};dda=function(a){if(a[0]==="-")return!1;const b=a.length;return b<20?!0:b===20&&Number(a.substring(0,6))<184467};eda=function(a){const b=a.length;return a[0]==="-"?b<20?!0:b===20&&Number(a.substring(0,7))>-922337:b<19?!0:b===19&&Number(a.substring(0,6))<922337};gda=function(a){if(a<0){_.aca(a);var b=dca(_.Oa,_.Pa);a=Number(b);return fda(a)?a:b}b=String(a);if(dda(b))return b;_.aca(a);return eca(_.Oa,_.Pa)};
hda=function(a){if(eda(a))return a;lca(a);return _.kca(_.Oa,_.Pa)};ida=function(a){if(dda(a))return a;lca(a);return dca(_.Oa,_.Pa)};ada=function(a){a=jda(a);fda(a)||(_.aca(a),a=fca(_.Oa,_.Pa));return a};kda=function(a){a=jda(a);return a>=0&&fda(a)?a:gda(a)};Yca=function(a){a=jda(a);if(fda(a))a=String(a);else{{const b=String(a);eda(b)?a=b:(_.aca(a),a=_.kca(_.Oa,_.Pa))}}return a};lda=function(a){a=jda(a);if(a>=0&&fda(a))a=String(a);else{{const b=String(a);dda(b)?a=b:(_.aca(a),a=dca(_.Oa,_.Pa))}}return a};
Wca=function(a){var b=jda(Number(a));if(fda(b))return String(b);b=a.indexOf(".");b!==-1&&(a=a.substring(0,b));return hda(a)};Zca=function(a){var b=jda(Number(a));if(fda(b))return _.Na(b);b=a.indexOf(".");b!==-1&&(a=a.substring(0,b));return Nba()?_.Na(Xca(64,BigInt(a))):_.Na(hda(a))};$ca=function(a){return fda(a)?_.Na(ada(a)):_.Na(Yca(a))};mda=function(a){return fda(a)?_.Na(kda(a)):_.Na(lda(a))};
nda=function(a){var b=jda(Number(a));if(fda(b)&&b>=0)return String(b);b=a.indexOf(".");b!==-1&&(a=a.substring(0,b));return ida(a)};pda=function(a){var b=jda(Number(a));if(fda(b)&&b>=0)return _.Na(b);b=a.indexOf(".");b!==-1&&(a=a.substring(0,b));return Nba()?_.Na(oda(64,BigInt(a))):_.Na(ida(a))};_.rda=function(a){if(a==null)return a;if(typeof a==="bigint")return qda(a)?a=Number(a):(a=Xca(64,a),a=qda(a)?Number(a):String(a)),a;if(Rca(a))return typeof a==="number"?ada(a):Wca(a)};
_.sda=function(a,b=!1){const c=typeof a;if(a==null)return a;if(c==="bigint")return String(Xca(64,a));if(Rca(a))return c==="string"?Wca(a):b?Yca(a):ada(a)};tda=function(a){const b=typeof a;if(a==null)return a;if(b==="bigint")return _.Na(Xca(64,a));if(Rca(a))return b==="string"?Zca(a):$ca(a)};
_.uda=function(a,b=0){if(!Rca(a))throw Gca("uint64");const c=typeof a;switch(b){case 512:switch(c){case "string":return nda(a);case "bigint":return String(oda(64,a));default:return lda(a)}case 1024:switch(c){case "string":return pda(a);case "bigint":return _.Na(oda(64,a));default:return mda(a)}case 0:switch(c){case "string":return nda(a);case "bigint":return _.Na(oda(64,a));default:return kda(a)}default:return _.Wa(b,"Unknown format requested type for int64")}};
_.vda=function(a){return a==null?a:_.uda(a,0)};_.wda=function(a){if(a==null)return a;if(typeof a==="bigint")return a>=0&&qda(a)?a=Number(a):(a=oda(64,a),a=qda(a)?Number(a):String(a)),a;if(Rca(a))return typeof a==="number"?kda(a):nda(a)};_.xda=function(a,b=!1){const c=typeof a;if(a==null)return a;if(c==="bigint")return String(oda(64,a));if(Rca(a))return c==="string"?nda(a):b?lda(a):kda(a)};
_.yda=function(a){const b=typeof a;if(a==null)return a;if(b==="bigint")return _.Na(oda(64,a));if(Rca(a))return b==="string"?pda(a):mda(a)};_.zda=function(a){if(a==null)return a;const b=typeof a;if(b==="bigint")return String(Xca(64,a));if(Rca(a)){if(b==="string")return Wca(a);if(b==="number")return ada(a)}};_.Ada=function(a){if(a==null)return a;const b=typeof a;if(b==="bigint")return String(oda(64,a));if(Rca(a)){if(b==="string")return nda(a);if(b==="number")return kda(a)}};
Bda=function(a){if(a==null||typeof a=="string"||a instanceof _.La)return a};Cda=function(a){if(typeof a!=="string")throw Error();return a};Dda=function(a){if(a!=null&&typeof a!=="string")throw Error();return a};Eda=function(a){return a==null||typeof a==="string"?a:void 0};_.Hda=function(a,b,c,d){if(_.sca(a))return a;if(!Array.isArray(a))return c?d&2?b[Fda]||(b[Fda]=Gda(b)):new b:void 0;c=a[_.Sa]|0;d=c|d&32|d&2;d!==c&&(a[_.Sa]=d);return new b(a)};Gda=function(a){a=new a;
